"""Module 11 - Enterprise Defender (EDR) Console.

A read-only console over the TelemetryStore: a severity-sorted alert queue, a
computed risk score, per-alert drill-down, MITRE mapping and containment actions.
"""
import streamlit as st

from modules.base_module import BaseModule
from components.ui import page_header, status_badge, metric_cards
from core.config import AppConfig
from core.state import AppState
from core.telemetry import TelemetryStore

_P = AppConfig.PALETTE

SEV_ORDER = {"Critical": 0, "High": 1, "Medium": 2}
SEV_WEIGHT = {"Critical": 45, "High": 25, "Medium": 10}
SEV_BADGE = {"Critical": "critical", "High": "warning", "Medium": "neutral"}
SEV_MARK = {"Critical": "\u2716", "High": "\u26a0", "Medium": "\u00b7"}

TACTIC_RECS = {
    "Execution": ["Kill the offending process tree", "Enable PowerShell ScriptBlock logging + Constrained Language Mode", "Investigate the parent process"],
    "Defense Evasion": ["Capture a memory image before reboot", "Scan for RWX private memory regions", "Check for unsigned or injected modules"],
    "Credential Access": ["Rotate exposed credentials immediately", "Enable LSASS protection (RunAsPPL) / Credential Guard", "Hunt for lateral movement with those credentials"],
    "Persistence": ["Remove the persistence entry", "Baseline all autoruns", "Check for additional persistence mechanisms"],
    "Command and Control": ["Block the C2 IP/domain at the firewall", "Isolate the affected host", "Determine the beacon interval and scope"],
    "Exfiltration": ["Block the exfiltration channel", "Assess what data was accessible", "Engage DLP and notify data owners"],
    "Impact": ["Isolate immediately to stop spread", "Verify offline backups are intact", "Activate the incident response and recovery plan"],
}


class EDRConsoleModule(BaseModule):
    @property
    def id(self) -> str:
        return "edr_console"

    @property
    def title(self) -> str:
        return "EDR Console"

    @property
    def icon(self) -> str:
        return "\U0001f6e1"

    @property
    def description(self) -> str:
        return "Detect, triage and contain the telemetry generated by the Attack Simulator."

    # ---- entry point ----
    def render(self) -> None:
        page_header("EDR Console", self.description, pill="Module 11")

        alerts = sorted(TelemetryStore.alerts(),
                        key=lambda a: (SEV_ORDER.get(a["severity"], 9), a["time"]))
        if not alerts:
            st.info("No detections yet. Open the **Attack Simulator** (Module 10), run one or "
                    "more attacks, then return here to triage the alerts.")
            return

        self._render_risk(alerts)
        self._render_metrics(alerts)

        ids = [a["id"] for a in alerts]
        if AppState.get("edr_selected") not in ids:
            AppState.set("edr_selected", ids[0])

        left, right = st.columns([1, 1.7], gap="large")
        with left:
            self._render_queue(alerts)
        with right:
            selected = next(a for a in alerts if a["id"] == AppState.get("edr_selected"))
            self._render_detail(selected)

    # ---- risk score + host status ----
    def _render_risk(self, alerts) -> None:
        score = min(100, sum(SEV_WEIGHT.get(a["severity"], 0) for a in alerts))
        level, color = self._risk_level(score)
        isolated = AppState.get("edr_isolated", False)

        cols = st.columns([2, 1])
        with cols[0]:
            st.markdown(
                f"""
                <div class="ps-card">
                  <div style="display:flex;align-items:baseline;gap:.6rem;">
                    <span style="font-size:2rem;font-weight:800;color:{color};">{score}</span>
                    <span class="ps-kv">/ 100 risk score</span>
                    <span style="margin-left:auto;">{status_badge(level, self._level_kind(level))}</span>
                  </div>
                  <div style="height:8px;background:{_P.border};border-radius:999px;overflow:hidden;margin-top:.6rem;">
                    <div style="width:{score}%;height:100%;background:{color};border-radius:999px;"></div>
                  </div>
                </div>
                """,
                unsafe_allow_html=True,
            )
        with cols[1]:
            host = ("Isolated", "critical") if isolated else ("Online", "success")
            st.markdown(
                f'<div class="ps-card" style="text-align:center;">'
                f'<div class="ps-kv">Host DESKTOP-PS</div>'
                f'<div style="margin:.3rem 0;">{status_badge(host[0], host[1])}</div></div>',
                unsafe_allow_html=True,
            )
            if not isolated:
                if st.button("Isolate host", type="primary", use_container_width=True):
                    AppState.set("edr_isolated", True)
                    st.rerun()
            else:
                if st.button("Release isolation", use_container_width=True):
                    AppState.set("edr_isolated", False)
                    st.rerun()

    # ---- metrics ----
    def _render_metrics(self, alerts) -> None:
        crit = sum(1 for a in alerts if a["severity"] == "Critical")
        high = sum(1 for a in alerts if a["severity"] == "High")
        metric_cards([
            ("Active alerts", str(len(alerts)), _P.accent),
            ("Critical", str(crit), _P.danger),
            ("High", str(high), _P.warning),
            ("Connections", str(len(TelemetryStore.connections())), _P.info),
        ])

    # ---- alert queue ----
    def _render_queue(self, alerts) -> None:
        st.markdown('<div class="ps-kv" style="margin:.4rem 0 .5rem;">Alert queue</div>',
                    unsafe_allow_html=True)
        for a in alerts:
            mark = SEV_MARK.get(a["severity"], "")
            active = a["id"] == AppState.get("edr_selected")
            if st.button(f"{mark}  {a['name']}  \u00b7  {a['time']}", key=f"edr_{a['id']}",
                         type="primary" if active else "secondary",
                         use_container_width=True):
                AppState.set("edr_selected", a["id"])
                st.rerun()

    # ---- alert detail ----
    def _render_detail(self, alert) -> None:
        name = alert["name"]
        events = [e for e in TelemetryStore.events() if e["attack"] == name]
        procs = [p for p in TelemetryStore.processes() if p.get("attack") == name]
        conns = [c for c in TelemetryStore.connections() if c.get("attack") == name]
        regs = [r for r in TelemetryStore.registry() if r.get("attack") == name]

        st.markdown(
            f"""
            <div class="ps-card">
              <div style="display:flex;align-items:center;gap:.4rem;flex-wrap:wrap;">
                <span style="font-weight:700;font-size:1.2rem;">{name}</span>
                {status_badge(alert["severity"], SEV_BADGE.get(alert["severity"], "neutral"))}
                {status_badge(alert["tactic"], "info")}
                <span class="ps-pill">{alert["technique"]}</span>
                <span class="ps-kv" style="margin-left:auto;">Detected {alert["time"]}</span>
              </div>
              <div style="margin-top:.6rem;">{alert["description"]}</div>
            </div>
            """,
            unsafe_allow_html=True,
        )

        t1, t2, t3, t4, t5 = st.tabs(["Timeline", "Processes", "Network", "Registry", "IOCs"])
        with t1:
            for e in events:
                st.markdown(f'`{e["time"]}` &nbsp; **{e["source"]} {e["event_id"]}** - {e["message"]}')
            if not events:
                st.caption("No events.")
        with t2:
            for p in procs:
                st.markdown(f'- **{p["name"]}** (PID {p["pid"]}, PPID {p["ppid"]}) `{p["cmdline"]}`')
            if not procs:
                st.caption("No process artifacts.")
        with t3:
            for c in conns:
                st.markdown(f'- **{c["process"]}** -> `{c["remote"]}:{c["port"]}` - {c["note"]}')
            if not conns:
                st.caption("No network artifacts.")
        with t4:
            for r in regs:
                st.markdown(f'- `{r["path"]}` -> **{r["value"]}** = `{r["data"]}`')
            if not regs:
                st.caption("No registry artifacts.")
        with t5:
            for ioc in alert.get("iocs", []):
                st.markdown(f'- `{ioc}`')

        self._render_recommendations(alert)
        self._render_containment(alert)

    # ---- recommendations ----
    def _render_recommendations(self, alert) -> None:
        recs = TACTIC_RECS.get(alert["tactic"], ["Investigate and scope the activity."])
        items = "".join(f'<li style="margin:.15rem 0;">{r}</li>' for r in recs)
        st.markdown(
            f'<div class="ps-card" style="background:{_P.accent_soft};border-left:3px solid {_P.accent};">'
            f'<div class="ps-kv" style="color:{_P.accent};">Recommended actions</div>'
            f'<ul style="margin:.4rem 0 0 1rem;padding:0;">{items}</ul></div>',
            unsafe_allow_html=True,
        )

    # ---- containment ----
    def _render_containment(self, alert) -> None:
        aid = alert["id"]
        taken = self._actions_for(aid)
        st.markdown('<div class="ps-kv" style="margin:.3rem 0 .4rem;">Containment</div>',
                    unsafe_allow_html=True)
        c1, c2, c3 = st.columns(3)
        with c1:
            if st.button("Kill processes", key=f"edr_kill_{aid}", use_container_width=True):
                self._add_action(aid, "Processes terminated")
                st.rerun()
        with c2:
            if st.button("Block IOCs", key=f"edr_block_{aid}", use_container_width=True):
                self._add_action(aid, "Network IOCs blocked")
                st.rerun()
        with c3:
            if st.button("Quarantine", key=f"edr_quar_{aid}", use_container_width=True):
                self._add_action(aid, "Artifacts quarantined")
                st.rerun()
        if taken:
            badges = " ".join(status_badge(t, "success") for t in taken)
            st.markdown(f'<div style="margin-top:.5rem;">{badges}</div>', unsafe_allow_html=True)

    # ---- containment state helpers ----
    @staticmethod
    def _actions_for(aid):
        return (AppState.get("edr_actions") or {}).get(aid, [])

    @staticmethod
    def _add_action(aid, action) -> None:
        data = AppState.get("edr_actions") or {}
        lst = data.get(aid, [])
        if action not in lst:
            lst.append(action)
        data[aid] = lst
        AppState.set("edr_actions", data)

    # ---- risk helpers ----
    @staticmethod
    def _risk_level(score):
        if score == 0:
            return "Secure", _P.success
        if score < 40:
            return "Guarded", _P.info
        if score < 70:
            return "Elevated", _P.warning
        return "Critical", _P.danger

    @staticmethod
    def _level_kind(level):
        return {"Secure": "success", "Guarded": "info", "Elevated": "warning", "Critical": "critical"}.get(level, "neutral")
